version: "3.9"

services:
  web:
    image: hadinsr/genai-rag-assistant:latest
    container_name: genai_web
    build: .
    ports:
      - "7870:7860"
    environment:
      - DATABASE_URL=postgresql+psycopg2://rag_role:mypassword@db:5432/rag_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
    restart: always

  # FastAPI service exposing OpenAPI docs at /docs
  #api:
    #build: .
    #command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    #ports:
      #- "8000:8000"
    #environment:
      #- DATABASE_URL=postgresql+psycopg2://rag_role:mypassword@db:5432/rag_db
      #- OPENAI_API_KEY=${OPENAI_API_KEY}
    #depends_on:
      #- db
    #restart: always
 

  db:
    image: postgres:16
    container_name: genai_db
    environment:
      POSTGRES_USER: rag_role
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data_new:

# to run: docker compose up --build
# to stop: docker compose down